"use client";

import { useState, useEffect } from "react";
import { usePosts } from '@/lib/useLocalPosts';
import type { Post } from '@/lib/types';
import styles from './blog.module.css';
import { FloatingNav } from '../components/FloatingNav';
import AdSenseDisplay from '../components/AdSenseDisplay';
import { Instagram, X, Video, Share2, Loader2 } from 'lucide-react';
import { useUser } from '@clerk/nextjs';
import { useRouter } from 'next/navigation';

const FALLBACK_IMG = 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop';

export default function BlogPage() {
  const { posts, refresh } = usePosts();
  const router = useRouter();
  const { isSignedIn } = useUser();
  const [signaling, setSignaling] = useState<Record<string, boolean>>({});

  useEffect(() => {
    const handleUpdate = () => refresh();
    window.addEventListener('posts-updated', handleUpdate);
    return () => window.removeEventListener('posts-updated', handleUpdate);
  }, [refresh]);

  const handleSignal = async (slug: string, platform: 'twitter' | 'instagram' | 'tiktok') => {
    try {
      setSignaling(prev => ({ ...prev, [`${slug}-${platform}`]: true }));
      const res = await fetch('/api/social', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ slug, platform })
      });
      const data = await res.json();
      if (data.success) {
        refresh();
      } else {
        alert(`Social Signal Failed: ${data.error || 'Unknown error'}`);
      }
    } catch (err) {
      console.error('Signal Error:', err);
    } finally {
      setSignaling(prev => ({ ...prev, [`${slug}-${platform}`]: false }));
    }
  };

  return (
    <main className={styles.blogContainer}>
      <FloatingNav />
      
      <div className={styles.blogContent}>
        <header className={styles.header}>
          <h1>Pulse Blog</h1>
          <p>Autonomous deep-dives generated by your Niche Engine.</p>
          {isSignedIn && (
            <div className={styles.authLinks}>
              <a href="/api/auth/tiktok/connect" className={styles.authLink}>🔗 Connect TikTok</a>
            </div>
          )}
        </header>

        {/* Display ad below blog header */}
        <AdSenseDisplay />

        {posts.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '100px 0', color: '#64748b' }}>
            <p>No pulses generated yet. Start a cycle in the main dashboard!</p>
          </div>
        ) : (
          <div className={styles.postGrid}>
             {posts.map((post: Post) => (
                <article 
                  className={styles.postCard} 
                  key={post.id} 
                  onClick={() => router.push(`/blog/${post.slug}`)}
                  style={{ cursor: 'pointer' }}
                >
                  <div className={styles.imageWrapper}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img 
                      src={post.ogImageUrl || FALLBACK_IMG} 
                      alt={post.title}
                      style={{ width: '100%', height: '210px', objectFit: 'cover', display: 'block' }}
                      onError={(e) => { (e.target as HTMLImageElement).src = FALLBACK_IMG; }}
                    />
                  </div>
                  <div className={styles.cardContent}>
                    <span className={styles.tag}>{post.keyword}</span>
                    <h2 className={styles.postTitle}>{post.title}</h2>
                    <p className={styles.excerpt}>{post.metaDescription}</p>
                    <div className={styles.cardFooter}>
                      <span className={styles.date}>
                        {new Date(post.publishedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </span>
                      <div className={styles.socialLinks} onClick={(e) => e.stopPropagation()}>
                        {post.instagramUrl ? (
                          <a href={post.instagramUrl} target="_blank" rel="noopener noreferrer" title="View on Instagram" className={styles.socialIconActive}>
                            <Instagram size={18} />
                          </a>
                        ) : (
                          isSignedIn && (
                            <button 
                              onClick={() => handleSignal(post.slug, 'instagram')}
                              disabled={signaling[`${post.slug}-instagram`]}
                              className={styles.signalButton}
                              title="Signal to Instagram"
                            >
                              {signaling[`${post.slug}-instagram`] ? <Loader2 size={14} className={styles.spin} /> : <Instagram size={14} />}
                              <span>Signal</span>
                            </button>
                          )
                        )}

                        {post.twitterUrl ? (
                          <a href={post.twitterUrl} target="_blank" rel="noopener noreferrer" title="View on X" className={styles.socialIconActive}>
                            <X size={18} />
                          </a>
                        ) : (
                          isSignedIn && (
                            <button 
                              onClick={() => handleSignal(post.slug, 'twitter')}
                              disabled={signaling[`${post.slug}-twitter`]}
                              className={styles.signalButton}
                              title="Signal to X"
                            >
                              {signaling[`${post.slug}-twitter`] ? <Loader2 size={14} className={styles.spin} /> : <X size={14} />}
                              <span>Signal</span>
                            </button>
                          )
                        )}

                        {post.tiktokUrl ? (
                          <a href={post.tiktokUrl} target="_blank" rel="noopener noreferrer" title="View on TikTok" className={styles.socialIconActive}>
                            <Video size={18} />
                          </a>
                        ) : (
                          isSignedIn && (
                            <button 
                              onClick={() => handleSignal(post.slug, 'tiktok')}
                              disabled={signaling[`${post.slug}-tiktok`]}
                              className={styles.signalButton}
                              title="Signal to TikTok"
                            >
                              {signaling[`${post.slug}-tiktok`] ? <Loader2 size={14} className={styles.spin} /> : <Video size={14} />}
                              <span>Signal</span>
                            </button>
                          )
                        )}
                      </div>
                      <span className={styles.readMore}>Read Pulse →</span>
                    </div>
                  </div>
                </article>
            ))}
          </div>
        )}

        {/* Display ad below posts grid */}
        {posts.length > 0 && <AdSenseDisplay />}
      </div>
    </main>
  );
}
