"use client";

import { usePosts } from '@/lib/useLocalPosts';
import Link from 'next/link';
import styles from './blog.module.css';
import { FloatingNav } from '../components/FloatingNav';

const FALLBACK_IMG = 'https://images.unsplash.com/photo-1451187580459-43490279c0fa?q=80&w=800&auto=format&fit=crop';

export default function BlogPage() {
  const { posts } = usePosts();

  return (
    <main className={styles.blogContainer}>
      <FloatingNav />
      
      <div className={styles.blogContent}>
        <header className={styles.header}>
          <h1>Pulse Blog</h1>
          <p>Autonomous deep-dives generated by your Niche Engine.</p>
        </header>

        {posts.length === 0 ? (
          <div style={{ textAlign: 'center', padding: '100px 0', color: '#64748b' }}>
            <p>No pulses generated yet. Start a cycle in the main dashboard!</p>
          </div>
        ) : (
          <div className={styles.postGrid}>
            {posts.map((post) => (
              <Link href={`/blog/${post.slug}`} key={post.id}>
                <article className={styles.postCard}>
                  <div className={styles.imageWrapper}>
                    {/* eslint-disable-next-line @next/next/no-img-element */}
                    <img 
                      src={post.ogImageUrl || FALLBACK_IMG} 
                      alt={post.title}
                      style={{ width: '100%', height: '210px', objectFit: 'cover', display: 'block' }}
                      onError={(e) => { (e.target as HTMLImageElement).src = FALLBACK_IMG; }}
                    />
                  </div>
                  <div className={styles.cardContent}>
                    <span className={styles.tag}>{post.keyword}</span>
                    <h2 className={styles.postTitle}>{post.title}</h2>
                    <p className={styles.excerpt}>{post.metaDescription}</p>
                    <div className={styles.cardFooter}>
                      <span className={styles.date}>
                        {new Date(post.publishedAt).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })}
                      </span>
                      <span className={styles.readMore}>Read Pulse →</span>
                    </div>
                  </div>
                </article>
              </Link>
            ))}
          </div>
        )}
      </div>
    </main>
  );
}
