import { FloatingNav } from "../components/FloatingNav";
import styles from "../page.module.css";
import localStyles from "./PrivacyPolicy.module.css";
import Link from "next/link";

export const metadata = {
  title: "Privacy Policy | The Niche Content Engine",
  description: "Privacy Policy for The Niche Content Engine and System Pulse operations.",
};

export default function PrivacyPage() {
  const lastUpdated = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  return (
    <main className={styles.main}>
      <FloatingNav />
      
      <div className={styles.header}>
        <h1 className={styles.title}>Privacy Policy</h1>
        <p className={styles.subtitle}>Commitment to data integrity and user transparency.</p>
      </div>

      <div className={localStyles.container}>
        <div className={localStyles.content}>
          <span className={localStyles.lastUpdated}>Last Updated: {lastUpdated}</span>

          <h2>1. Introduction</h2>
          <p>
            The Niche Content Engine ("we", "our", or "the platform") is committed to protecting your privacy. 
            This Privacy Policy explains how we collect, use, and safeguard information when you use our 
            autonomous content generation and social signaling features.
          </p>

          <h2>2. Information We Collect</h2>
          <h3>2.1 Personal Information</h3>
          <p>
            We may collect information you provide directly, such as your name, email address, and 
            API credentials (e.g., Meta/Instagram, X/Twitter, OpenAI) required to operate the platform's 
            autonomous agents.
          </p>
          
          <h3>2.2 Meta/Instagram & TikTok Data</h3>
          <p>
            When you connect your Instagram Business Account or TikTok account, we access specific data via their respective APIs 
            to perform social signaling tasks. This includes:
          </p>
          <ul>
            <li>Your Instagram Business Account ID and TikTok Open ID.</li>
            <li>Media metadata for posts generated by the engine.</li>
            <li>Basic profile information required for authentication and token management.</li>
          </ul>
          <p>
            We do not store your private messages, follower lists, or any data not explicitly required 
            for the "Social Signaling" feature.
          </p>

          <h2>3. How We Use Your Information</h2>
          <p>We use the collected data to:</p>
          <ul>
            <li>Operate the AI-driven content cycle (Discovery, Reasoning, SEO).</li>
            <li>Publish content to your connected social media platforms.</li>
            <li>Provide diagnostic feedback on API connectivity and quota usage.</li>
            <li>Improve the performance and accuracy of our autonomous agents.</li>
          </ul>

          <h2>4. Data Storage and Security</h2>
          <p>
            Your API credentials and project data are stored securely. We implement industry-standard 
            encryption and security measures to protect against unauthorized access, alteration, or 
            disclosure of your information.
          </p>

          <h2>5. Third-Party Services</h2>
          <p>
            The platform integrates with several third-party AI and social media providers, including 
            Meta (Facebook/Instagram), X (Twitter), Google (Gemini/Search Console), and Groq. Your 
            interactions with these services are governed by their respective privacy policies.
          </p>

          <h2>6. Data Retention and Deletion</h2>
          <p>
            We retain your information as long as your account is active or as needed to provide 
            services. You may request the deletion of your data and the revocation of API access 
            at any time through the platform's settings or by contacting us.
          </p>

          <h2>7. Contact Us</h2>
          <p>
            If you have any questions about this Privacy Policy, please contact our support team 
            through the System Pulse dashboard.
          </p>
          
          <Link href="/" className={localStyles.backLink}>
            ← Back to Dashboard
          </Link>
        </div>
      </div>
    </main>
  );
}
