import { FloatingNav } from "../components/FloatingNav";
import styles from "../page.module.css";
import localStyles from "../privacy/PrivacyPolicy.module.css";
import Link from "next/link";

export const metadata = {
  title: "Terms of Service | The Niche Content Engine",
  description: "Terms of Service for The Niche Content Engine and System Pulse operations.",
};

export default function TermsPage() {
  const lastUpdated = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' });

  return (
    <main className={styles.main}>
      <FloatingNav />
      
      <div className={styles.header}>
        <h1 className={styles.title}>Terms of Service</h1>
        <p className={styles.subtitle}>Legal framework for autonomous content operations.</p>
      </div>

      <div className={localStyles.container}>
        <div className={localStyles.content}>
          <span className={localStyles.lastUpdated}>Last Updated: {lastUpdated}</span>

          <h2>1. Acceptance of Terms</h2>
          <p>
            By accessing or using The Niche Content Engine ("the Platform"), you agree to be bound by 
            these Terms of Service. If you do not agree to these terms, do not use the Platform.
          </p>

          <h2>2. Use of Service</h2>
          <p>
            The Platform provides autonomous content generation and social media signaling services. 
            You are responsible for:
          </p>
          <ul>
            <li>Maintaining the confidentiality of your API keys and credentials.</li>
            <li>Ensuring that the content generated and published complies with the terms of service of 
                third-party platforms (Meta, TikTok, X).</li>
            <li>The legality and accuracy of the content published through your accounts.</li>
          </ul>

          <h2>3. Intellectual Property</h2>
          <p>
            The software, AI agent logic, and "System Pulse" dashboard are the intellectual property of 
            the Platform. The content generated (articles, images) is licensed to you for use on your 
            connected blogs and social media profiles.
          </p>

          <h2>4. Content Disclaimer</h2>
          <p>
            Content is generated by AI agents (Groq, Gemini, OpenAI). While we strive for accuracy and 
            SEO optimization, we do not guarantee that the content is error-free or will result in 
            specific traffic or revenue outcomes. Use of generated content is at your own risk.
          </p>

          <h2>5. API Usage and Rate Limits</h2>
          <p>
            You agree not to abuse the API connections or attempt to circumvent rate limits established 
            by the Platform or third-party providers. Violation of these limits may result in 
            temporary or permanent suspension of your autonomous cycle access.
          </p>

          <h2>6. Limitation of Liability</h2>
          <p>
            The Platform shall not be liable for any indirect, incidental, or consequential damages 
            arising out of your use of the autonomous agents, including but not limited to 
            social media account suspensions or loss of data.
          </p>

          <h2>7. Changes to Terms</h2>
          <p>
            We reserve the right to modify these terms at any time. Your continued use of the Platform 
            after such modifications constitutes acceptance of the updated terms.
          </p>

          <h2>8. Contact</h2>
          <p>
            Questions regarding these terms should be directed to the support team via the 
            System Pulse dashboard.
          </p>
          
          <Link href="/" className={localStyles.backLink}>
            ← Back to Dashboard
          </Link>
        </div>
      </div>
    </main>
  );
}
